import { build } from 'esbuild';
import assert from 'node:assert/strict';
const bundle=await build({stdin:{contents:"export * from './lib/analyzer'; export * from './lib/demo'; export * from './lib/connector';",resolveDir:process.cwd(),loader:'ts'},bundle:true,format:'esm',platform:'node',write:false});
const {parseSource,analyze,demoSources,percentile,validateEndpoint,publicAddress,reportMarkdown}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const demo=demoSources(),findings=analyze(demo);
assert.equal(findings.length,4);assert.equal(findings.filter(f=>f.severity==='High').length,2);
assert.ok(findings.some(f=>f.signal==='12% error events'));assert.ok(findings.some(f=>f.title==='Right-size underused compute'));
assert.equal(percentile([1,2,3,4,5,6,7,8,9,10],.95),10);
const logs=Array.from({length:50},(_,i)=>JSON.stringify({service:'api',level:i<10?'ERROR':'INFO',message:i<10?'request failed':'request done',duration_ms:i<5?1500:100})).join('\n');
const logSource=parseSource(logs,'events.ndjson');const logFindings=analyze([logSource]);
assert.equal(logSource.logs.length,50);assert.ok(logFindings.some(f=>f.signal==='20% error events'));assert.ok(logFindings.some(f=>f.signal==='1,500 ms p95'));
assert.equal(parseSource(logs+'\n{bad}').notes[0],'1 malformed JSON lines were skipped.');
const splunk=parseSource('{"preview":true,"result":{"_raw":"ERROR early"}}\n{"preview":false,"result":{"_raw":"{\\"service\\":\\"api\\",\\"level\\":\\"ERROR\\",\\"message\\":\\"failed\\"}"}}');
assert.equal(splunk.type,'Splunk');assert.equal(splunk.logs.length,1);assert.equal(splunk.logs[0].service,'api');assert.equal(splunk.logs[0].level,'ERROR');
const csv=parseSource('service,level,message,duration_ms\napi,ERROR,"failed, on query\nretry",1800\napi,INFO,ok,20');assert.equal(csv.logs.length,2);assert.equal(csv.logs[0].durationMs,1800);assert.ok(csv.logs[0].message.includes('\n'));
assert.throws(()=>parseSource('service,level,message\na,INFO'),/fields/);
const prom={status:'success',data:{resultType:'matrix',result:[{metric:{instance:'node-a'},values:Array.from({length:25},(_,i)=>[i*3600,String(.1+i%3*.01)])}]}};
const p=parseSource(JSON.stringify(prom),'cpu.json','prometheus','cpu_ratio');assert.equal(p.metrics[0].kind,'cpu');assert.equal(p.metrics[0].values[0][1],10);assert.equal(analyze([p]).length,1);
const unknown=parseSource(JSON.stringify(prom));assert.equal(analyze([unknown]).length,0);assert.ok(unknown.notes.some(n=>n.includes('unknown units')));
const snapshot=parseSource('node_cpu_usage_percent{instance="node-a"} 10','metrics','prometheus');assert.equal(analyze([snapshot]).length,0);
const counter=parseSource('node_cpu_seconds_total{instance="node-a",mode="idle"} 95180','metrics','prometheus');assert.equal(analyze([counter]).length,0);
const high=parseSource('node_memory_usage_percent{instance="node-a"} 92');assert.ok(analyze([high]).some(f=>f.title==='Investigate memory pressure'));
const raw=parseSource('2026-09-24T12:00:00Z ERROR service=api status=502 duration=1.5s upstream timeout');assert.equal(raw.logs[0].durationMs,1500);assert.equal(raw.logs[0].service,'api');
assert.throws(()=>parseSource(''),/Add metrics/);assert.throws(()=>parseSource('{invalid json}'),/No usable data/);assert.throws(()=>parseSource(JSON.stringify({status:'error',error:'bad query'})),/API error/);
assert.throws(()=>validateEndpoint('http://127.0.0.1:9090'),/HTTPS/);assert.throws(()=>validateEndpoint('https://localhost:9090'),/public DNS/);assert.throws(()=>validateEndpoint('https://2130706433'),/public DNS/);assert.throws(()=>validateEndpoint('https://user:secret@metrics.acme.com'),/without credentials/);assert.throws(()=>validateEndpoint('https://[::1]'),/public DNS/);
assert.equal(validateEndpoint('https://metrics.acme.com/prometheus').pathname,'/prometheus/');assert.equal(publicAddress('10.0.0.1'),false);assert.equal(publicAddress('172.20.0.1'),false);assert.equal(publicAddress('169.254.169.254'),false);assert.equal(publicAddress('100.100.100.200'),false);assert.equal(publicAddress('8.8.8.8'),true);assert.equal(publicAddress('::ffff:127.0.0.1'),false);assert.equal(publicAddress('fd00::1'),false);
const report=reportMarkdown(demo);assert.ok(report.includes('SAMPLE DATA'));assert.ok(report.includes('No infrastructure changes have been made'));assert.ok(report.includes('error events'));
console.log('Passed: 37 checks covering measured findings, units, false positives, imports, export, and endpoint validation.');
